apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: udagram-api-frontend
  name: udagram-api-frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: udagram-api-frontend
    spec:
      containers:
      - image: onojatreasure/udagram-api-frontend
        name: udagram-api-frontend
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"       
        ports:
        - containerPort: 8080
      restartPolicy: Always
